import pandas as pd

# Load per‑epoch loss (generated by parse_loss.py)
df = pd.read_csv("epoch_loss.csv")

# Número de últimas épocas a analisar (padrão 10)
N = 10
window = df.tail(N)

# Variação percentual entre a primeira e a última loss da janela
pct_change = abs(window["loss"].iloc[-1] - window["loss"].iloc[0]) / window["loss"].iloc[0] * 100
print(f"Variação percentual nas últimas {N} épocas: {pct_change:.2f}%")

# Média móvel de 5 épocas para visualização
df["loss_ma5"] = df["loss"].rolling(5).mean()

df.to_csv("epoch_loss_metrics.csv", index=False)
print("Métricas salvas em epoch_loss_metrics.csv")
