import pandas as pd
import matplotlib.pyplot as plt

# Load the metrics generated by convergence_check.py
df = pd.read_csv("epoch_loss_metrics.csv")

plt.figure(figsize=(10, 5))
plt.plot(df["epoch"], df["loss"], label="Loss por época", marker='o')
plt.plot(df["epoch"], df["loss_ma5"], label="Média móvel (5)", linestyle='--')
plt.xlabel('Época')
plt.ylabel('Loss (média)')
plt.title('Curva de perda durante o treinamento')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.savefig('loss_curve.png')
plt.show()
